print("HELLO FROM SULTAN")
print("HELLO FROM NAZAR")
print("HELLO FROM ALIYA")
print('hewefwerfew')
print('ergergre')
print('ewgergregrergregeer')
print('wfreegrrgtrrgt')
print('fegfrgvfsfewge')
print('regergersawdgs')